apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gb-rollout
  annotations: 
    codefresh.io/product: demo
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    path: guestbooks/guestbook-rollout
    repoURL: https://github.com/oleksandr-codefresh/argocd-example-apps
    targetRevision: personal-eks
  destination:
    # name: in-cluster
    name: scale-prod
    namespace: demo-ns
  syncPolicy:
    automated:
      prune: true
      # selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
