apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
 name: argo-cd-monitoring
 finalizers:
   - resources-finalizer.argocd.argoproj.io/foreground
spec:
 project: default
 source:
   path: notifications
   repoURL: https://github.com/oleksandr-codefresh/argo-load-monitoring
   targetRevision: maim
 destination:
   name: in-cluster
   namespace: argo-load
 syncPolicy:
   automated:
     prune: true
     selfHeal: false
     allowEmpty: true
   syncOptions:
     - PrunePropagationPolicy=foreground
     - Replace=false
     - PruneLast=false
     - Validate=true
     - CreateNamespace=true
     - ApplyOutOfSyncOnly=false
     - ServerSideApply=true
     - RespectIgnoreDifferences=false
