# apiVersion: monitoring.coreos.com/v1alpha1
# kind: ScrapeConfig
# metadata:
#   name: scrape-config-argo-events
#   labels:
#     release: prometheus
# spec:
#   scrapeInterval: 30s
#   kubernetesSdConfigs:
#     - role: pod
#       selectors:
#       - role: pod
#         label: 'controller in (eventsource-controller,sensor-controller,eventbus-controller)'
#   relabelConfigs:
#     - sourceLabels: [__meta_kubernetes_pod_label_eventbus_name, __meta_kubernetes_pod_label_controller]
#       action: replace
#       regex: (.+);eventbus-controller
#       replacement: $1
#       targetLabel: 'eventbus_name'
#     - sourceLabels: [__meta_kubernetes_namespace, __meta_kubernetes_pod_label_controller]
#       action: replace
#       regex: (.+);eventbus-controller
#       replacement: $1
#       targetLabel: 'namespace'
#     - sourceLabels: [__address__, __meta_kubernetes_pod_label_controller]
#       action: drop
#       regex: (.+):(\d222);eventbus-controller
      
