apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: argo-events-resources-pod-monitor
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
    - argo-load
  selector:
    matchExpressions:
      - key: controller
        operator: in
        values:
        - eventsource-controller
        - sensor-controller
        - eventbus-controller
  podMetricsEndpoints:
  - port: metrics
      
