---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: event-reporter
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: event-reporter
      app.kubernetes.io/name: argocd-metrics
  namespaceSelector:
    matchNames:
    - argo-load
  endpoints:
  - port: http-metrics
