{
 "title": "Codefresh argo-cd events reporter (v2)",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "reporter_shard",
    "label": "Shard number",
    "query": {
     "query": "label_values(cf_e_reporter_queue_size,reporter_shard)"
    }
   },
   {
    "name": "metric_event_type",
    "label": "Metric event type",
    "query": {
     "query": "label_values(cf_e_reporter_event_processing_duration_bucket,metric_event_type)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current queue size",
   "type": "stat",
   "gridPos": { "h": 11, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cf_e_reporter_queue_size{job=\"event-reporter-metrics\"}",
     "legendFormat": "{{reporter_shard}}"
    }
   ]
  },
  {
   "title": "Queue size delta (1m)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 20, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(cf_e_reporter_queue_size{job=\"event-reporter-metrics\"}[1m])",
     "legendFormat": "{{reporter_shard}}"
    }
   ]
  },
  {
   "title": "Events stats of shard - $reporter_shard",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Errored events",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(error_type) (increase(cf_e_reporter_errored_events{reporter_shard=\"$reporter_shard\"}[10m]))"
    }
   ]
  },
  {
   "title": "Cached ignored application events",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(cf_e_reporter_cached_ignored_events{ job=\"event-reporter-metrics\", metric_event_type=\"app\"}[10m])",
     "legendFormat": "{{reporter_shard}}"
    }
   ]
  },
  {
   "title": "Cached ignored resource events",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(cf_e_reporter_cached_ignored_events{reporter_shard=\"$reporter_shard\", metric_event_type=\"resource\"}[10m])"
    }
   ]
  },
  {
   "title": "Performance of shard - $reporter_shard",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 }
  },
  {
   "title": "Parent app event performance (s)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "sum by(le) (increase(cf_e_reporter_event_processing_duration_bucket{metric_event_type=\"parent_app\", reporter_shard=\"$reporter_shard\"}[10m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Child app event performance (s)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "sum by(le) (increase(cf_e_reporter_event_processing_duration_bucket{job=\"event-reporter-metrics\", metric_event_type=\"child_app\", reporter_shard=\"$reporter_shard\"}[10m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Resource event performance (s)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "sum by(le) (increase(cf_e_reporter_event_processing_duration_bucket{metric_event_type=\"resource\", reporter_shard=\"$reporter_shard\"}[10m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Go stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Used",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_alloc_bytes{source=\"cf-event-reporter\"}"
      }
     ]
    },
    {
     "title": "Amount of go routines",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_goroutines{source=\"cf-event-reporter\"}"
      }
     ]
    },
    {
     "title": "Number of OS threads created",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_threads{source=\"cf-event-reporter\"}"
      }
     ]
    }
   ]
  }
 ]
}