apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: scrape-config-event-reporter
  labels:
    release: prometheus
spec:
  scrapeInterval: 10s
  scheme: HTTP
  staticConfigs:
    - labels:
        job: prometheus
        source: cf-event-reporter
      targets:
      - 712e1a77678c.ngrok.app
